services:
    nginxproxymanager:
        image: 'jc21/nginx-proxy-manager:latest'
        container_name: nginxproxymanager
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./nginx/data:/data
            - ./nginx/letsencrypt:/etc/letsencrypt

    idlerpg:
        image: 'ghcr.io/frederikja163/idlerpg:latest'
        pull_policy: always
        container_name: idlerpg
        restart: unless-stopped
        ports:
            - '4022:22'
            - '4000:4000'
        environment:
            - SSH_USER=${IDLERPG_SSH_USER}
            - SSH_PUBLIC_KEY=${IDLERPG_SSH_PUBLIC_KEY}
            - TLS_CERT_PATH=/certs/live/npm-2/fullchain.pem
            - TLS_KEY_PATH=/certs/live/npm-2/privkey.pem
        volumes:
            - ./nginx/letsencrypt:/certs:ro
            - idle-rpg-data:/usr/src/idle-rpg/src/back-end/core/db

    jellyfin:
        image: linuxserver/jellyfin:latest
        container_name: jellyfin
        restart: unless-stopped
        ports:
            - '8096:8096'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Copenhagen
        volumes:
            - jellyfin_config:/config
            - ./nginx/letsencrypt:/certs:ro
            - '/media/SeagateHub/Film og serier/Film:/data/Film'
            - '/media/SeagateHub/Film og serier/Serier:/data/Serier'

volumes:
    idle-rpg-data:
    jellyfin_config:
